default:
  input_path: "/Users/mraj/Desktop/work/data/forMukund/allRDSs"
  op_path: "output/ss/nUMI_v2/"
  mapping_data: "input/mapping_data.tsv"

current:
  input_path: "/Users/mraj/Desktop/work/data/forMukund/allRDSs"

slide_seq:
  ip_path_ss: "/Users/mraj/Desktop/work/data/mouse_atlas/data_v3_nissl_post_qc/s0_raw_data/slide_seq_imgs"
  op_rescaled_ss: "/Users/mraj/Desktop/work/data/mouse_atlas/data_v3_nissl_post_qc/s0_start_formatted_data/slide_seq_imgs_rescaled" 
