## Main file for processing integrated Seurat object generated by Jonah by
## integrating bead coords in CCF and gene expression data for all pucks
## 
## Created by Mukund on 2022-05-03

install.packages("anndata")
library(qs)
library(anndata)


setwd("/home/mraj/Desktop/work/projects/active/broad-registration")
data_path <- "/home/mraj/data/forMukund/2022-05-03/11_allSeurats_CCF.qs"


# read in Seurat object
df1 = qread(data_path)
obsnames <- rownames(df1[[1]]@assays$Spatial@counts)


for (ssid in seq(67, 207, 2)){
  
  dfid = (ssid+1)/2 # data frame id
  if (ssid>=167 ){
    dfid = (ssid-5)/2
  }else if(ssid>=77){
    dfid=(ssid-3)/2
  }else if(ssid>=5){
    dfid = (ssid-2)/2;
  }

  
  varnames1 <- colnames(df1[[dfid]]@assays$Spatial@counts)
  ad_counts_1 <- AnnData(X = df1[[dfid]]@assays$Spatial@counts,
                         obs = data.frame(row.names=obsnames ),
                         var = data.frame(row.names=varnames1))
  ad_coords_1 <- AnnData(X = df1[[dfid]]@images$image@coordinates )
  
  op_counts_file = paste0("output/integrated_mats/ad_counts_", ssid, ".h5ad")
  op_coords_file = paste0("output/integrated_mats/ad_coords_", ssid, ".h5ad")
  print(op_counts_file)
  print(op_coords_file)
  write_h5ad(anndata=ad_counts_1, filename=op_counts_file, compression="gzip")
  write_h5ad(anndata=ad_coords_1, filename=op_coords_file, compression="gzip")

}



# useful info about qc data object
# df1[[1]] - first Seurat object

# df1[[1]]@assays$Spatial@counts - gene counts (gene/dim1 x barcode/dim2)
# df1[[1]]@assays$Spatial@counts@Dimnames
# df1[[1]]@seurat.obj@meta.data - misc other per cell data

# copy command as template
# scp -r [external ip]:~/Desktop/work/projects/active/broad-registration/output/integrated_mats ~/Desktop/work/data/temp_data/2022-05-04/